spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false


server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_SERVICE}:8761/eureka/
    register-with-eureka: false   # Eureka server itself does not register
    fetch-registry: false   # Eureka server does not need to fetch the registry


    #defaultZone: http://localhost:8761/eureka/


