spring:
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/project-service/**
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/task-service/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.address}/auth/realms/cydeo-dev

keycloak:
  address: http://localhost:8080

server:
  port: 8762

eureka:
  instance:
    preferIpAddress: true
    ipAddress: 127.0.0.1
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
  context-path: http://localhost:${server.port}/actuator

info:
  application:
    name: gateway-service
    description: Ticketing Application Gateway Service

springdoc:
  swagger-ui:
    urls:
      - name: User Service API Doc
        url: /user-service/v3/api-docs
      - name: Project Service API Doc
        url: /project-service/v3/api-docs
      - name: Task Service API Doc
        url: /task-service/v3/api-docs




